import type { GovernanceSeed } from "./governance.types.js";

const now = "2026-07-12T18:30:00.000Z";

export const governanceDemoSeed: GovernanceSeed = {
  approvals: [
    {
      id: "ap_01",
      channelId: "ch_historia",
      entityType: "visual_plan",
      entityId: "vp_01",
      title: "Aprovar plano visual - Astecas",
      status: "blocked",
      riskLevel: "blocked",
      summary: "Bloqueado porque a cobertura de cenas ainda nao fecha com o plano.",
      requestedAt: "2026-07-12T10:00:00.000Z",
      requestedBy: "Ana Ribeiro",
      createdAt: "2026-07-12T10:00:00.000Z",
      updatedAt: "2026-07-12T10:00:00.000Z",
      targetSnapshot: {
        entityType: "visual_plan",
        entityId: "vp_01",
        channelId: "ch_historia",
        title: "Plano visual - Astecas",
        summary: "Composicao cinematografica, cores quentes e mapas texturizados.",
        status: "visual_plan",
        riskLevel: "blocked",
      },
      qualityCheckId: "qc_03",
      complianceCheckId: "cc_04",
    },
    {
      id: "ap_02",
      channelId: "ch_historia",
      entityType: "script",
      entityId: "sc_01",
      title: "Aprovar roteiro - Como os astecas mediam o tempo",
      status: "approved",
      riskLevel: "ok",
      summary: "Roteiro consistente e sem bloqueios relevantes.",
      requestedAt: "2026-07-11T18:22:00.000Z",
      requestedBy: "Ana Ribeiro",
      decidedAt: "2026-07-11T18:50:00.000Z",
      decidedBy: "Ana Ribeiro",
      decisionReason: "Roteiro consistente e com CTA pronto.",
      createdAt: "2026-07-11T18:22:00.000Z",
      updatedAt: "2026-07-11T18:50:00.000Z",
      targetSnapshot: {
        entityType: "script",
        entityId: "sc_01",
        channelId: "ch_historia",
        title: "Como os astecas mediam o tempo",
        summary: "Um calendario que organiza o cosmos e a politica em um unico sistema.",
        status: "script",
        riskLevel: "ok",
      },
      qualityCheckId: "qc_01",
      complianceCheckId: "cc_01",
      latestDecisionId: "ad_01",
    },
    {
      id: "ap_03",
      channelId: "ch_curiosidades",
      entityType: "content_idea",
      entityId: "idea_03",
      title: "Rejeitar pauta - Por que dormimos?",
      status: "rejected",
      riskLevel: "attention",
      summary: "Pauta com necessidade de ajuste de enquadramento e evidencias adicionais.",
      requestedAt: "2026-07-12T09:10:00.000Z",
      requestedBy: "Bruno Lima",
      decidedAt: "2026-07-12T09:30:00.000Z",
      decidedBy: "Bruno Lima",
      decisionReason: "Necessita revisao editorial antes de seguir.",
      createdAt: "2026-07-12T09:10:00.000Z",
      updatedAt: "2026-07-12T09:30:00.000Z",
      targetSnapshot: {
        entityType: "content_idea",
        entityId: "idea_03",
        channelId: "ch_curiosidades",
        title: "Por que dormimos? A hipotese sinaptica",
        summary: "Explicacao atual sobre a funcao restaurativa do sono e evidencias.",
        status: "editing",
        riskLevel: "attention",
      },
      qualityCheckId: "qc_04",
      complianceCheckId: "cc_03",
      latestDecisionId: "ad_02",
    },
    {
      id: "ap_04",
      channelId: "ch_historia",
      entityType: "research_session",
      entityId: "rs_01",
      title: "Solicitar alteracoes - Fontes de Constantinopla",
      status: "changes_requested",
      riskLevel: "attention",
      summary: "A sessao precisa complementar a cobranca de fonte com URL explicita.",
      requestedAt: "2026-07-12T11:00:00.000Z",
      requestedBy: "Ana Ribeiro",
      decidedAt: "2026-07-12T11:25:00.000Z",
      decidedBy: "Ana Ribeiro",
      decisionReason: "Adicionar URL na fonte principal e revisar o resumo.",
      createdAt: "2026-07-12T11:00:00.000Z",
      updatedAt: "2026-07-12T11:25:00.000Z",
      targetSnapshot: {
        entityType: "research_session",
        entityId: "rs_01",
        channelId: "ch_historia",
        title: "Fontes e cronologia - Constantinopla 1453",
        summary: "Fontes primarias e cronologia consolidada para o cerco final.",
        status: "running",
        riskLevel: "attention",
      },
      qualityCheckId: "qc_02",
      complianceCheckId: "cc_02",
      latestDecisionId: "ad_03",
    },
    {
      id: "ap_05",
      channelId: "ch_curiosidades",
      entityType: "production_item",
      entityId: "pi_idea_03",
      title: "Fila de aprovacao - Item em edicao",
      status: "pending",
      riskLevel: "attention",
      summary: "Item ainda em edicao, com revisao operacional pendente.",
      requestedAt: "2026-07-12T13:45:00.000Z",
      requestedBy: "Bruno Lima",
      createdAt: "2026-07-12T13:45:00.000Z",
      updatedAt: "2026-07-12T13:45:00.000Z",
      targetSnapshot: {
        entityType: "production_item",
        entityId: "pi_idea_03",
        channelId: "ch_curiosidades",
        title: "Por que dormimos? A hipotese sinaptica",
        summary: "Detalhar cenas",
        status: "editing",
        riskLevel: "attention",
      },
      qualityCheckId: "qc_05",
      complianceCheckId: "cc_05",
    },
  ],
  approvalDecisions: [
    {
      id: "ad_01",
      approvalId: "ap_02",
      previousStatus: "pending",
      nextStatus: "approved",
      decision: "approve",
      justification: "Roteiro consistente e com CTA pronto.",
      actor: "Ana Ribeiro",
      decidedAt: "2026-07-11T18:50:00.000Z",
      createdAt: "2026-07-11T18:50:00.000Z",
    },
    {
      id: "ad_02",
      approvalId: "ap_03",
      previousStatus: "pending",
      nextStatus: "rejected",
      decision: "reject",
      justification: "Necessita revisao editorial antes de seguir.",
      actor: "Bruno Lima",
      decidedAt: "2026-07-12T09:30:00.000Z",
      createdAt: "2026-07-12T09:30:00.000Z",
    },
    {
      id: "ad_03",
      approvalId: "ap_04",
      previousStatus: "pending",
      nextStatus: "changes_requested",
      decision: "request_changes",
      justification: "Adicionar URL na fonte principal e revisar o resumo.",
      actor: "Ana Ribeiro",
      decidedAt: "2026-07-12T11:25:00.000Z",
      createdAt: "2026-07-12T11:25:00.000Z",
    },
  ],
  qualityChecks: [
    {
      id: "qc_01",
      channelId: "ch_historia",
      entityType: "script",
      entityId: "sc_01",
      status: "passed",
      score: 96,
      checks: [
        {
          code: "title_present",
          name: "Titulo presente",
          result: "pass",
          severity: "ok",
          message: "Titulo confirmado.",
          blocking: false,
          metadata: { field: "title" },
        },
        {
          code: "hook_present",
          name: "Hook presente",
          result: "pass",
          severity: "ok",
          message: "Hook confirmado.",
          blocking: false,
          metadata: { field: "hook" },
        },
        {
          code: "cta_present",
          name: "CTA presente",
          result: "pass",
          severity: "ok",
          message: "CTA confirmado.",
          blocking: false,
          metadata: { field: "cta" },
        },
      ],
      findings: [],
      blockingFindings: [],
      checkedAt: "2026-07-11T18:40:00.000Z",
      createdAt: "2026-07-11T18:40:00.000Z",
      updatedAt: "2026-07-11T18:40:00.000Z",
      targetSnapshot: {
        entityType: "script",
        entityId: "sc_01",
        channelId: "ch_historia",
        title: "Como os astecas mediam o tempo",
        summary: "Um calendario que organiza o cosmos e a politica em um unico sistema.",
        status: "script",
        riskLevel: "ok",
      },
      summary: "Roteiro pronto para gate humano.",
    },
    {
      id: "qc_02",
      channelId: "ch_historia",
      entityType: "research_session",
      entityId: "rs_01",
      status: "attention",
      score: 82,
      checks: [
        {
          code: "source_count",
          name: "Fontes registradas",
          result: "pass",
          severity: "ok",
          message: "Fontes confirmadas.",
          blocking: false,
          metadata: { sourceCount: 2 },
        },
        {
          code: "source_url_coverage",
          name: "Cobertura de URL",
          result: "attention",
          severity: "attention",
          message: "Algumas fontes ainda nao possuem URL.",
          blocking: false,
          metadata: { missingSourceIds: ["src_02"] },
        },
      ],
      findings: [
        {
          code: "source_url_coverage",
          name: "Cobertura de URL",
          result: "attention",
          severity: "attention",
          message: "Algumas fontes ainda nao possuem URL.",
          blocking: false,
          metadata: { missingSourceIds: ["src_02"] },
        },
      ],
      blockingFindings: [],
      checkedAt: "2026-07-12T10:50:00.000Z",
      createdAt: "2026-07-12T10:50:00.000Z",
      updatedAt: "2026-07-12T10:50:00.000Z",
      targetSnapshot: {
        entityType: "research_session",
        entityId: "rs_01",
        channelId: "ch_historia",
        title: "Fontes e cronologia - Constantinopla 1453",
        summary: "Fontes primarias e cronologia consolidada para o cerco final.",
        status: "running",
        riskLevel: "attention",
      },
      summary: "Sessao com fonte sem URL explicita.",
    },
    {
      id: "qc_03",
      channelId: "ch_historia",
      entityType: "visual_plan",
      entityId: "vp_01",
      status: "blocked",
      score: 55,
      checks: [
        {
          code: "title_present",
          name: "Titulo presente",
          result: "pass",
          severity: "ok",
          message: "Titulo confirmado.",
          blocking: false,
          metadata: { field: "title" },
        },
        {
          code: "style_present",
          name: "Estilo visual presente",
          result: "pass",
          severity: "ok",
          message: "Estilo confirmado.",
          blocking: false,
          metadata: { field: "visualStyle" },
        },
        {
          code: "scene_coverage",
          name: "Cobertura de cenas",
          result: "blocked",
          severity: "blocked",
          message: "A quantidade de cenas planejadas nao confere com o plano.",
          blocking: true,
          metadata: { sceneCount: 8, actualScenes: 2 },
        },
      ],
      findings: [
        {
          code: "scene_coverage",
          name: "Cobertura de cenas",
          result: "blocked",
          severity: "blocked",
          message: "A quantidade de cenas planejadas nao confere com o plano.",
          blocking: true,
          metadata: { sceneCount: 8, actualScenes: 2 },
        },
      ],
      blockingFindings: [
        {
          code: "scene_coverage",
          name: "Cobertura de cenas",
          result: "blocked",
          severity: "blocked",
          message: "A quantidade de cenas planejadas nao confere com o plano.",
          blocking: true,
          metadata: { sceneCount: 8, actualScenes: 2 },
        },
      ],
      checkedAt: "2026-07-12T10:55:00.000Z",
      createdAt: "2026-07-12T10:55:00.000Z",
      updatedAt: "2026-07-12T10:55:00.000Z",
      targetSnapshot: {
        entityType: "visual_plan",
        entityId: "vp_01",
        channelId: "ch_historia",
        title: "Plano visual - Astecas",
        summary: "Composicao cinematografica, cores quentes e mapas texturizados.",
        status: "visual_plan",
        riskLevel: "blocked",
      },
      summary: "Plano visual ainda nao fecha com as cenas planejadas.",
    },
    {
      id: "qc_04",
      channelId: "ch_curiosidades",
      entityType: "content_idea",
      entityId: "idea_03",
      status: "attention",
      score: 88,
      checks: [
        {
          code: "title_present",
          name: "Titulo presente",
          result: "pass",
          severity: "ok",
          message: "Titulo confirmado.",
          blocking: false,
          metadata: { field: "title" },
        },
        {
          code: "opportunity_score",
          name: "Oportunidade",
          result: "attention",
          severity: "attention",
          message: "A oportunidade editorial pede revisao.",
          blocking: false,
          metadata: { opportunityScore: 82 },
        },
      ],
      findings: [
        {
          code: "opportunity_score",
          name: "Oportunidade",
          result: "attention",
          severity: "attention",
          message: "A oportunidade editorial pede revisao.",
          blocking: false,
          metadata: { opportunityScore: 82 },
        },
      ],
      blockingFindings: [],
      checkedAt: now,
      createdAt: now,
      updatedAt: now,
      targetSnapshot: {
        entityType: "content_idea",
        entityId: "idea_03",
        channelId: "ch_curiosidades",
        title: "Por que dormimos? A hipotese sinaptica",
        summary: "Explicacao atual sobre a funcao restaurativa do sono e evidencias.",
        status: "editing",
        riskLevel: "attention",
      },
      summary: "Pauta pede refinamento editorial.",
    },
    {
      id: "qc_05",
      channelId: "ch_curiosidades",
      entityType: "production_item",
      entityId: "pi_idea_03",
      status: "attention",
      score: 90,
      checks: [
        {
          code: "title_present",
          name: "Titulo presente",
          result: "pass",
          severity: "ok",
          message: "Titulo confirmado.",
          blocking: false,
          metadata: { field: "title" },
        },
        {
          code: "next_action_present",
          name: "Proxima acao presente",
          result: "pass",
          severity: "ok",
          message: "Proxima acao confirmada.",
          blocking: false,
          metadata: { field: "nextAction" },
        },
        {
          code: "progress_maturity",
          name: "Maturidade do fluxo",
          result: "attention",
          severity: "attention",
          message: "O item ainda esta abaixo do nivel desejado de conclusao.",
          blocking: false,
          metadata: { progressPercent: 74 },
        },
      ],
      findings: [
        {
          code: "progress_maturity",
          name: "Maturidade do fluxo",
          result: "attention",
          severity: "attention",
          message: "O item ainda esta abaixo do nivel desejado de conclusao.",
          blocking: false,
          metadata: { progressPercent: 74 },
        },
      ],
      blockingFindings: [],
      checkedAt: now,
      createdAt: now,
      updatedAt: now,
      targetSnapshot: {
        entityType: "production_item",
        entityId: "pi_idea_03",
        channelId: "ch_curiosidades",
        title: "Por que dormimos? A hipotese sinaptica",
        summary: "Detalhar cenas",
        status: "editing",
        riskLevel: "attention",
      },
      summary: "Item operacional ainda em edicao.",
    },
  ],
  complianceChecks: [
    {
      id: "cc_01",
      channelId: "ch_historia",
      entityType: "script",
      entityId: "sc_01",
      status: "approved",
      riskLevel: "ok",
      findings: [],
      blockingFindings: [],
      checkedAt: "2026-07-11T18:42:00.000Z",
      createdAt: "2026-07-11T18:42:00.000Z",
      updatedAt: "2026-07-11T18:42:00.000Z",
      targetSnapshot: {
        entityType: "script",
        entityId: "sc_01",
        channelId: "ch_historia",
        title: "Como os astecas mediam o tempo",
        summary: "Um calendario que organiza o cosmos e a politica em um unico sistema.",
        status: "script",
        riskLevel: "ok",
      },
      requiresHumanReview: false,
    },
    {
      id: "cc_02",
      channelId: "ch_historia",
      entityType: "research_session",
      entityId: "rs_01",
      status: "needs_human_review",
      riskLevel: "attention",
      findings: [
        {
          code: "source_url_missing",
          name: "URL ausente",
          severity: "attention",
          message: "Algumas fontes nao trazem URL explicita.",
          blocking: false,
          metadata: { sourceIds: ["src_02"] },
        },
      ],
      blockingFindings: [],
      checkedAt: "2026-07-12T10:52:00.000Z",
      createdAt: "2026-07-12T10:52:00.000Z",
      updatedAt: "2026-07-12T10:52:00.000Z",
      targetSnapshot: {
        entityType: "research_session",
        entityId: "rs_01",
        channelId: "ch_historia",
        title: "Fontes e cronologia - Constantinopla 1453",
        summary: "Fontes primarias e cronologia consolidada para o cerco final.",
        status: "running",
        riskLevel: "attention",
      },
      requiresHumanReview: true,
    },
    {
      id: "cc_03",
      channelId: "ch_curiosidades",
      entityType: "content_idea",
      entityId: "idea_03",
      status: "attention",
      riskLevel: "attention",
      findings: [
        {
          code: "needs_review",
          name: "Revisao humana",
          severity: "attention",
          message: "A pauta pede revisao humana antes do avancar.",
          blocking: false,
          metadata: { opportunityScore: 82 },
        },
      ],
      blockingFindings: [],
      checkedAt: now,
      createdAt: now,
      updatedAt: now,
      targetSnapshot: {
        entityType: "content_idea",
        entityId: "idea_03",
        channelId: "ch_curiosidades",
        title: "Por que dormimos? A hipotese sinaptica",
        summary: "Explicacao atual sobre a funcao restaurativa do sono e evidencias.",
        status: "editing",
        riskLevel: "attention",
      },
      requiresHumanReview: true,
    },
    {
      id: "cc_04",
      channelId: "ch_historia",
      entityType: "visual_plan",
      entityId: "vp_01",
      status: "blocked",
      riskLevel: "blocked",
      findings: [
        {
          code: "scene_mismatch",
          name: "Cenas inconsistentes",
          severity: "blocked",
          message: "O plano visual nao confere com o numero de cenas registradas.",
          blocking: true,
          metadata: { sceneCount: 8, actualScenes: 2 },
        },
      ],
      blockingFindings: [
        {
          code: "scene_mismatch",
          name: "Cenas inconsistentes",
          severity: "blocked",
          message: "O plano visual nao confere com o numero de cenas registradas.",
          blocking: true,
          metadata: { sceneCount: 8, actualScenes: 2 },
        },
      ],
      checkedAt: "2026-07-12T10:56:00.000Z",
      createdAt: "2026-07-12T10:56:00.000Z",
      updatedAt: "2026-07-12T10:56:00.000Z",
      targetSnapshot: {
        entityType: "visual_plan",
        entityId: "vp_01",
        channelId: "ch_historia",
        title: "Plano visual - Astecas",
        summary: "Composicao cinematografica, cores quentes e mapas texturizados.",
        status: "visual_plan",
        riskLevel: "blocked",
      },
      requiresHumanReview: true,
    },
    {
      id: "cc_05",
      channelId: "ch_curiosidades",
      entityType: "production_item",
      entityId: "pi_idea_03",
      status: "attention",
      riskLevel: "attention",
      findings: [
        {
          code: "production_attention",
          name: "Atencao operacional",
          severity: "attention",
          message: "O item de producao ainda pede atencao.",
          blocking: false,
          metadata: { progressPercent: 74 },
        },
      ],
      blockingFindings: [],
      checkedAt: now,
      createdAt: now,
      updatedAt: now,
      targetSnapshot: {
        entityType: "production_item",
        entityId: "pi_idea_03",
        channelId: "ch_curiosidades",
        title: "Por que dormimos? A hipotese sinaptica",
        summary: "Detalhar cenas",
        status: "editing",
        riskLevel: "attention",
      },
      requiresHumanReview: false,
    },
  ],
};
