import type { CostSeed } from "./costs.types.js";

const now = "2026-07-13T03:30:00.000Z";

export const costsDemoSeed: CostSeed = {
  costEntries: [
    {
      id: "co_01",
      channelId: "ch_historia",
      contentId: "idea_02",
      workflowRunId: "wf_02",
      stage: "script",
      providerName: "Aralume AI",
      costType: "llm",
      description: "Roteirista - 3 iteracoes",
      amountCents: 4200,
      currency: "BRL",
      createdAt: "2026-07-10T11:00:00.000Z",
    },
    {
      id: "co_02",
      channelId: "ch_historia",
      contentId: "idea_02",
      stage: "narration",
      providerName: "Aralume TTS",
      costType: "tts",
      description: "Narracao final Asteca",
      amountCents: 1740,
      currency: "BRL",
      createdAt: "2026-07-11T14:19:00.000Z",
    },
    {
      id: "co_03",
      channelId: "ch_historia",
      contentId: "idea_06",
      stage: "visual_plan",
      providerName: "Aralume Vision",
      costType: "image",
      description: "18 cenas - Logistica Romana",
      amountCents: 5760,
      currency: "BRL",
      createdAt: "2026-07-08T10:00:00.000Z",
    },
    {
      id: "co_04",
      channelId: "ch_historia",
      contentId: "idea_06",
      stage: "render",
      providerName: "Aralume Render",
      costType: "render",
      description: "Render final 1080p",
      amountCents: 3400,
      currency: "BRL",
      createdAt: "2026-07-11T13:20:00.000Z",
    },
    {
      id: "co_05",
      channelId: "ch_curiosidades",
      contentId: "idea_03",
      stage: "editorial",
      providerName: "Aralume AI",
      costType: "llm",
      description: "Roteirista + Editorial",
      amountCents: 6100,
      currency: "BRL",
      createdAt: "2026-07-10T09:00:00.000Z",
    },
    {
      id: "co_06",
      channelId: "ch_curiosidades",
      contentId: "idea_03",
      stage: "production",
      providerName: "StockCo",
      costType: "video",
      description: "B-roll licenciado",
      amountCents: 1800,
      currency: "BRL",
      createdAt: "2026-07-12T09:00:00.000Z",
    },
    {
      id: "co_07",
      channelId: "ch_curiosidades",
      contentId: "idea_04",
      stage: "script",
      providerName: "Aralume AI",
      costType: "llm",
      description: "Pesquisa + Roteiro",
      amountCents: 12800,
      currency: "BRL",
      createdAt: "2026-07-08T09:00:00.000Z",
    },
    {
      id: "co_08",
      channelId: "ch_curiosidades",
      stage: "infrastructure",
      providerName: "Aralume Storage",
      costType: "storage",
      description: "Armazenamento mensal",
      amountCents: 2400,
      currency: "BRL",
      createdAt: "2026-07-01T00:00:00.000Z",
    },
    {
      id: "co_09",
      channelId: "ch_negocios",
      stage: "editorial",
      providerName: "Aralume AI",
      costType: "llm",
      description: "Analise de mercado inicial",
      amountCents: 9400,
      currency: "BRL",
      createdAt: "2026-07-09T08:30:00.000Z",
    },
    {
      id: "co_10",
      channelId: "ch_negocios",
      stage: "production",
      providerName: "StockCo",
      costType: "video",
      description: "Case de mercado com b-roll licenciado",
      amountCents: 4200,
      currency: "BRL",
      createdAt: "2026-07-12T08:30:00.000Z",
    },
  ],
  operationalModePolicies: [
    {
      id: "op_global",
      scope: "global",
      mode: "demo",
      allowRealAi: false,
      allowRealTts: false,
      allowRealImageGeneration: false,
      allowRealVideoGeneration: false,
      allowExternalPublication: false,
      requireHumanApproval: true,
      budgetConfigured: false,
      dailyBudgetLimitCents: 0,
      monthlyBudgetLimitCents: 0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "op_ch_historia",
      scope: "channel",
      channelId: "ch_historia",
      mode: "demo",
      allowRealAi: false,
      allowRealTts: false,
      allowRealImageGeneration: false,
      allowRealVideoGeneration: false,
      allowExternalPublication: false,
      requireHumanApproval: true,
      budgetConfigured: true,
      dailyBudgetLimitCents: 7000,
      monthlyBudgetLimitCents: 20000,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "op_ch_curiosidades",
      scope: "channel",
      channelId: "ch_curiosidades",
      mode: "demo",
      allowRealAi: false,
      allowRealTts: false,
      allowRealImageGeneration: false,
      allowRealVideoGeneration: false,
      allowExternalPublication: false,
      requireHumanApproval: true,
      budgetConfigured: true,
      dailyBudgetLimitCents: 8000,
      monthlyBudgetLimitCents: 25000,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "op_ch_negocios",
      scope: "channel",
      channelId: "ch_negocios",
      mode: "demo",
      allowRealAi: false,
      allowRealTts: false,
      allowRealImageGeneration: false,
      allowRealVideoGeneration: false,
      allowExternalPublication: false,
      requireHumanApproval: true,
      budgetConfigured: true,
      dailyBudgetLimitCents: 3000,
      monthlyBudgetLimitCents: 10000,
      createdAt: now,
      updatedAt: now,
    },
  ],
};
