import type { EditorialSeed } from "./editorial.types.js";

const now = "2026-07-12T14:32:00.000Z";

export const editorialDemoSeed: EditorialSeed = {
  contentIdeas: [
    {
      id: "idea_01",
      channelId: "ch_historia",
      title: "A queda de Constantinopla contada em 12 minutos",
      summary: "Reconstrucao dos ultimos dias da capital bizantina com foco em decisoes.",
      niche: "Idade Media",
      source: "Britannica + Cambridge Medieval History",
      opportunityScore: 87,
      originalityScore: 74,
      visualPotentialScore: 91,
      clipPotentialScore: 82,
      riskLevel: "ok",
      status: "research",
      createdAt: "2026-07-08T12:00:00.000Z",
      updatedAt: "2026-07-11T09:15:00.000Z",
    },
    {
      id: "idea_02",
      channelId: "ch_historia",
      title: "Como os astecas mediam o tempo",
      summary: "Calendario sagrado, calendario civil e a engenharia por tras do sistema.",
      niche: "Antiguidade",
      source: "USP + Britannica",
      opportunityScore: 78,
      originalityScore: 88,
      visualPotentialScore: 84,
      clipPotentialScore: 79,
      riskLevel: "ok",
      status: "script",
      createdAt: "2026-07-04T10:00:00.000Z",
      updatedAt: "2026-07-11T18:22:00.000Z",
    },
    {
      id: "idea_03",
      channelId: "ch_curiosidades",
      title: "Por que dormimos? A hipotese sinaptica",
      summary: "Explicacao atual sobre a funcao restaurativa do sono e evidencias.",
      niche: "Corpo humano",
      source: "Nature Neuroscience",
      opportunityScore: 82,
      originalityScore: 69,
      visualPotentialScore: 71,
      clipPotentialScore: 88,
      riskLevel: "attention",
      status: "editing",
      createdAt: "2026-07-06T14:20:00.000Z",
      updatedAt: "2026-07-12T11:02:00.000Z",
    },
  ],
  productionItems: [
    {
      id: "pi_idea_01",
      channelId: "ch_historia",
      contentId: "idea_01",
      title: "A queda de Constantinopla contada em 12 minutos",
      status: "research",
      workflowRunId: "wf_idea_01",
      currentAgentId: "agent_research",
      currentAgentName: "Pesquisador",
      progressPercent: 25,
      costActualCents: 5210,
      riskLevel: "ok",
      nextAction: "Registrar fontes",
      lastActivityAt: "2026-07-12T13:58:00.000Z",
    },
    {
      id: "pi_idea_02",
      channelId: "ch_historia",
      contentId: "idea_02",
      title: "Como os astecas mediam o tempo",
      status: "script",
      workflowRunId: "wf_idea_02",
      currentAgentId: "agent_script",
      currentAgentName: "Roteirista",
      progressPercent: 60,
      costActualCents: 11640,
      riskLevel: "ok",
      nextAction: "Criar plano visual",
      lastActivityAt: "2026-07-11T18:22:00.000Z",
    },
    {
      id: "pi_idea_03",
      channelId: "ch_curiosidades",
      contentId: "idea_03",
      title: "Por que dormimos? A hipotese sinaptica",
      status: "editing",
      workflowRunId: "wf_idea_03",
      currentAgentId: "agent_visual",
      currentAgentName: "Direcao Visual",
      progressPercent: 74,
      costActualCents: 18320,
      riskLevel: "attention",
      nextAction: "Detalhar cenas",
      lastActivityAt: "2026-07-12T11:02:00.000Z",
    },
  ],
  researchSessions: [
    {
      id: "rs_01",
      channelId: "ch_historia",
      contentId: "idea_01",
      title: "Fontes e cronologia - Constantinopla 1453",
      status: "running",
      sourceCount: 2,
      claimCount: 3,
      confidenceScore: 82,
      riskLevel: "ok",
      summary: "Fontes primarias e cronologia consolidada para o cerco final.",
      createdAt: "2026-07-09T10:00:00.000Z",
      updatedAt: "2026-07-12T13:20:00.000Z",
    },
    {
      id: "rs_02",
      channelId: "ch_historia",
      contentId: "idea_02",
      title: "Calendarios astecas - fontes primarias",
      status: "completed",
      sourceCount: 2,
      claimCount: 2,
      confidenceScore: 88,
      riskLevel: "ok",
      summary: "Base factual suficiente para roteiro e plano visual.",
      createdAt: "2026-07-05T10:00:00.000Z",
      updatedAt: "2026-07-08T18:00:00.000Z",
    },
  ],
  researchSources: [
    {
      id: "src_01",
      channelId: "ch_historia",
      researchSessionId: "rs_01",
      title: "Britannica - Constantinople",
      url: "https://www.britannica.com/place/Constantinople-historical-empire-ancient-city-Turkey",
      publisher: "Britannica",
      accessedAt: now,
      sourceType: "official",
      confidenceLevel: "high",
      freshnessRisk: "ok",
      usageNotes: "Linha cronologica e contexto geopolitico.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "src_02",
      channelId: "ch_historia",
      researchSessionId: "rs_01",
      title: "Cambridge Medieval History",
      publisher: "Cambridge University Press",
      accessedAt: now,
      sourceType: "book",
      confidenceLevel: "high",
      freshnessRisk: "ok",
      usageNotes: "Detalhes taticos do cerco.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "src_03",
      channelId: "ch_historia",
      researchSessionId: "rs_02",
      title: "USP - Calendarios mesoamericanos",
      publisher: "USP",
      accessedAt: now,
      sourceType: "official",
      confidenceLevel: "high",
      freshnessRisk: "ok",
      usageNotes: "Sistema de contagem e calendario civil.",
      createdAt: now,
      updatedAt: now,
    },
  ],
  claimEvidence: [
    {
      id: "ce_01",
      channelId: "ch_historia",
      researchSessionId: "rs_01",
      sourceId: "src_01",
      claim: "Constantinopla resistiu ate maio de 1453 com defensores em numero muito menor.",
      evidenceSummary:
        "Fontes convergem para a superioridade numerica otomana e a defesa prolongada.",
      informationType: "fact",
      confidenceLevel: "high",
      riskLevel: "ok",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "ce_02",
      channelId: "ch_historia",
      researchSessionId: "rs_01",
      sourceId: "src_02",
      claim: "As muralhas e a artilharia foram fatores decisivos no desfecho do cerco.",
      evidenceSummary:
        "Trechos historicos e analises modernas descrevem a combinacao de tecnologia e logistica.",
      informationType: "fact",
      confidenceLevel: "high",
      riskLevel: "ok",
      createdAt: now,
      updatedAt: now,
    },
  ],
  scripts: [
    {
      id: "sc_01",
      channelId: "ch_historia",
      contentId: "idea_02",
      title: "Como os astecas mediam o tempo",
      status: "script",
      currentVersionId: "scv_01_v2",
      estimatedDurationSeconds: 720,
      hook: "Um calendario que organiza o cosmos e a politica em um unico sistema.",
      promise: "Voce vai entender como dois calendarios sustentavam o mundo asteca.",
      cta: "Assista a proxima parte da serie sobre astecas.",
      riskLevel: "ok",
      createdAt: "2026-07-05T10:00:00.000Z",
      updatedAt: "2026-07-11T18:22:00.000Z",
    },
  ],
  scriptVersions: [
    {
      id: "scv_01_v1",
      channelId: "ch_historia",
      scriptId: "sc_01",
      versionNumber: 1,
      title: "Como os astecas mediam o tempo - v1",
      narrationText: "Versao inicial do roteiro com estrutura basica.",
      sceneCount: 7,
      estimatedDurationSeconds: 690,
      changeSummary: "Estrutura inicial e gancho principal.",
      createdAt: "2026-07-08T09:00:00.000Z",
    },
    {
      id: "scv_01_v2",
      channelId: "ch_historia",
      scriptId: "sc_01",
      versionNumber: 2,
      title: "Como os astecas mediam o tempo - v2",
      narrationText: "Versao revisada com clareza narrativa e CTA final.",
      sceneCount: 8,
      estimatedDurationSeconds: 720,
      changeSummary: "Ajuste de tom e ampliacao da secao final.",
      createdAt: "2026-07-11T18:22:00.000Z",
    },
  ],
  visualPlans: [
    {
      id: "vp_01",
      channelId: "ch_historia",
      contentId: "idea_02",
      scriptVersionId: "scv_01_v2",
      title: "Plano visual - Astecas",
      status: "visual_plan",
      sceneCount: 8,
      estimatedDurationSeconds: 720,
      visualStyle: "Composicao cinematografica, cores quentes e mapas texturizados.",
      createdAt: "2026-07-11T18:40:00.000Z",
      updatedAt: "2026-07-11T18:40:00.000Z",
    },
  ],
  scenePlans: [
    {
      id: "scn_01",
      channelId: "ch_historia",
      visualPlanId: "vp_01",
      order: 1,
      title: "Abertura",
      narrationExcerpt: "Um calendario que nao era apenas tempo.",
      durationSeconds: 45,
      visualDescription: "Mapa mesoamericano com elementos em movimento.",
      assetRequirements: ["mapa", "tela de titulo"],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "scn_02",
      channelId: "ch_historia",
      visualPlanId: "vp_01",
      order: 2,
      title: "Calendario sagrado",
      narrationExcerpt: "A engrenagem ritual e astronomica.",
      durationSeconds: 60,
      visualDescription: "Calendario em close com camadas de simbolos.",
      assetRequirements: ["graficos", "overlay tipografico"],
      createdAt: now,
      updatedAt: now,
    },
  ],
};
