import type {
  DerivedClip,
  MediaAssetBase,
  MediaAssetsSeed,
  VideoAsset,
} from "./media-assets.types.js";
import { buildInternalUri } from "./media-assets.storage.js";

const now = "2026-07-12T13:44:00.000Z";

function mediaUri(channelId: string, assetId: string): string {
  return buildInternalUri(channelId, assetId);
}

const mediaAssets: MediaAssetBase[] = [
  {
    id: "ma_hist_narration_01",
    channelId: "ch_historia",
    type: "narration",
    category: "audio",
    name: "Narration - Constantinopla",
    title: "Narration - Constantinopla",
    description: "Narration master for the Constantinople episode.",
    mimeType: "audio/wav",
    extension: "wav",
    sizeBytes: 18_240_448,
    checksumAlgorithm: "sha256",
    checksum: "9b54a5e3a7e5c3df8b7f3b4e6c9d8f8b1d4cbf6d0f7b8d39f01d6a8d9a0c1b2a",
    internalUri: mediaUri("ch_historia", "ma_hist_narration_01"),
    storagePath: "ch_historia/narration/ma_hist_narration_01.wav",
    origin: "generated",
    provenance: "Created internally by the narration pipeline.",
    licenseStatus: "confirmed",
    status: "available",
    riskLevel: "ok",
    costActualCents: 1740,
    contentId: "idea_01",
    workflowRunId: "wf_01",
    scriptId: "sc_01",
    providerName: "Aralume TTS",
    modelName: "aralume-voice-v3",
    usageSummary: "Primary narration master for the content idea.",
    integrity: {
      checksumAlgorithm: "sha256",
      checksum: "9b54a5e3a7e5c3df8b7f3b4e6c9d8f8b1d4cbf6d0f7b8d39f01d6a8d9a0c1b2a",
      sizeBytes: 18_240_448,
      lastValidatedAt: now,
      checksumMatches: true,
      sizeMatches: true,
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ma_hist_image_01",
    channelId: "ch_historia",
    type: "image",
    category: "visual",
    name: "Templo Mayor frame",
    title: "Templo Mayor frame",
    description: "Key visual for the Aztec calendar segment.",
    mimeType: "image/jpeg",
    extension: "jpg",
    sizeBytes: 2_048_192,
    checksumAlgorithm: "sha256",
    checksum: "a0f3b6c5d4e1f9029c3f8a1c5e7d6b1a0d4f3e2c1b9a8d7c6e5f4a3b2c1d0e9f",
    internalUri: mediaUri("ch_historia", "ma_hist_image_01"),
    storagePath: "ch_historia/image/ma_hist_image_01.jpg",
    origin: "generated",
    provenance: "Internally generated reference frame.",
    licenseStatus: "known",
    status: "available",
    riskLevel: "ok",
    costActualCents: 320,
    contentId: "idea_02",
    workflowRunId: "wf_02",
    scriptId: "sc_01",
    providerName: "Aralume Vision",
    modelName: "aralume-img-v2",
    prompt: "Templo Mayor ao amanhecer, cinematic framing",
    usageSummary: "Used as the main illustrated scene for the script.",
    integrity: {
      checksumAlgorithm: "sha256",
      checksum: "a0f3b6c5d4e1f9029c3f8a1c5e7d6b1a0d4f3e2c1b9a8d7c6e5f4a3b2c1d0e9f",
      sizeBytes: 2_048_192,
      lastValidatedAt: now,
      checksumMatches: true,
      sizeMatches: true,
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ma_curio_video_01",
    channelId: "ch_curiosidades",
    type: "video",
    category: "video",
    name: "B-roll - Brain sleep",
    title: "B-roll - Brain sleep",
    description: "Licensed stock b-roll used for sleep episode transitions.",
    mimeType: "video/mp4",
    extension: "mp4",
    sizeBytes: 44_124_220,
    checksumAlgorithm: "sha256",
    checksum: "3c4a2d1b8f7e6d5c4b3a29180706050403020100ffeeddccbbaa998877665544",
    internalUri: mediaUri("ch_curiosidades", "ma_curio_video_01"),
    storagePath: "ch_curiosidades/video/ma_curio_video_01.mp4",
    origin: "licensed",
    provenance: "Licensed from stock library with documented usage rights.",
    licenseStatus: "pending",
    licenseName: "StockCo standard license",
    status: "pending",
    riskLevel: "attention",
    costActualCents: 1_800,
    contentId: "idea_03",
    workflowRunId: "wf_03",
    providerName: "StockCo",
    usageSummary: "Supporting b-roll for the episode.",
    integrity: {
      checksumAlgorithm: "sha256",
      checksum: "3c4a2d1b8f7e6d5c4b3a29180706050403020100ffeeddccbbaa998877665544",
      sizeBytes: 44_124_220,
      lastValidatedAt: now,
      checksumMatches: true,
      sizeMatches: true,
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ma_curio_thumb_01",
    channelId: "ch_curiosidades",
    type: "thumbnail",
    category: "visual",
    name: "Thumb - Fermi",
    title: "Thumb - Fermi",
    description: "Blocked thumbnail variant waiting for compliant wording.",
    mimeType: "image/png",
    extension: "png",
    sizeBytes: 812_448,
    checksumAlgorithm: "sha256",
    checksum: "7d6c5b4a3928171605f4e3d2c1b0a99887766554433221100ffeeddccbbaa99",
    internalUri: mediaUri("ch_curiosidades", "ma_curio_thumb_01"),
    storagePath: "ch_curiosidades/thumbnail/ma_curio_thumb_01.png",
    origin: "generated",
    provenance: "Internal draft thumbnail for review.",
    licenseStatus: "blocked",
    status: "blocked",
    riskLevel: "critical",
    costActualCents: 240,
    contentId: "idea_04",
    workflowRunId: "wf_04",
    providerName: "Aralume Vision",
    usageSummary: "Draft thumbnail pending compliance changes.",
    integrity: {
      checksumAlgorithm: "sha256",
      checksum: "7d6c5b4a3928171605f4e3d2c1b0a99887766554433221100ffeeddccbbaa99",
      sizeBytes: 812_448,
      lastValidatedAt: now,
      checksumMatches: true,
      sizeMatches: true,
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ma_hist_music_01",
    channelId: "ch_historia",
    type: "soundtrack",
    category: "audio",
    name: "Epic restrained track",
    title: "Epic restrained track",
    description: "Licensed soundtrack with attribution requirement.",
    mimeType: "audio/mpeg",
    extension: "mp3",
    sizeBytes: 9_944_100,
    checksumAlgorithm: "sha256",
    checksum: "c1d2e3f40516273849aabbccddeeff00112233445566778899aabbccddeeff00",
    internalUri: mediaUri("ch_historia", "ma_hist_music_01"),
    storagePath: "ch_historia/audio/ma_hist_music_01.mp3",
    origin: "licensed",
    provenance: "Licensed soundtrack with traceable source record.",
    licenseStatus: "attribution_required",
    licenseName: "MusicPool attribution license",
    status: "available",
    riskLevel: "ok",
    costActualCents: 900,
    usageSummary: "Background music for historical episodes.",
    integrity: {
      checksumAlgorithm: "sha256",
      checksum: "c1d2e3f40516273849aabbccddeeff00112233445566778899aabbccddeeff00",
      sizeBytes: 9_944_100,
      lastValidatedAt: now,
      checksumMatches: true,
      sizeMatches: true,
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ma_curio_caption_01",
    channelId: "ch_curiosidades",
    type: "subtitle",
    category: "text",
    name: "PT-BR captions",
    title: "PT-BR captions",
    description: "Subtitle file for the sleep episode.",
    mimeType: "text/vtt",
    extension: "vtt",
    sizeBytes: 48_228,
    checksumAlgorithm: "sha256",
    checksum: "0f1e2d3c4b5a697887969594939291908f8e7d6c5b4a39281716151413121110",
    internalUri: mediaUri("ch_curiosidades", "ma_curio_caption_01"),
    storagePath: "ch_curiosidades/text/ma_curio_caption_01.vtt",
    origin: "generated",
    provenance: "Generated captions prepared from the approved narration.",
    licenseStatus: "known",
    status: "available",
    riskLevel: "ok",
    costActualCents: 80,
    contentId: "idea_03",
    workflowRunId: "wf_03",
    usageSummary: "Caption track for the published episode.",
    integrity: {
      checksumAlgorithm: "sha256",
      checksum: "0f1e2d3c4b5a697887969594939291908f8e7d6c5b4a39281716151413121110",
      sizeBytes: 48_228,
      lastValidatedAt: now,
      checksumMatches: true,
      sizeMatches: true,
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ma_hist_aux_01",
    channelId: "ch_historia",
    type: "auxiliary",
    category: "auxiliary",
    name: "Reference map export",
    title: "Reference map export",
    description: "Auxiliary export used by the editorial team.",
    mimeType: "application/zip",
    extension: "zip",
    sizeBytes: 3_402_812,
    checksumAlgorithm: "sha256",
    checksum: "11223344556677889900aabbccddeeff11223344556677889900aabbccddeeff",
    internalUri: mediaUri("ch_historia", "ma_hist_aux_01"),
    storagePath: "ch_historia/auxiliary/ma_hist_aux_01.zip",
    origin: "uploaded",
    provenance: "Uploaded by the operations team.",
    licenseStatus: "not_applicable",
    status: "missing",
    riskLevel: "attention",
    costActualCents: 0,
    notes: "Registry entry retained even when the source file is missing.",
    integrity: {
      checksumAlgorithm: "sha256",
      checksum: "11223344556677889900aabbccddeeff11223344556677889900aabbccddeeff",
      sizeBytes: 3_402_812,
      lastValidatedAt: now,
      checksumMatches: false,
      sizeMatches: false,
    },
    createdAt: now,
    updatedAt: now,
  },
];

const videoAssets: VideoAsset[] = [
  {
    id: "vd_historia_01",
    channelId: "ch_historia",
    contentId: "idea_06",
    title: "A logistica do Imperio Romano",
    status: "published",
    durationSeconds: 842,
    format: "horizontal",
    resolution: "1920x1080",
    thumbnailUri: mediaUri("ch_historia", "ma_hist_image_01"),
    renderStatus: "rendered",
    qualityStatus: "passed",
    complianceStatus: "approved",
    costActualCents: 28_400,
    type: "video",
    origin: "generated",
    licenseStatus: "confirmed",
    internalUri: mediaUri("ch_historia", "vd_historia_01"),
    storagePath: "ch_historia/video/vd_historia_01.mp4",
    mimeType: "video/mp4",
    sizeBytes: 128_441_208,
    checksumAlgorithm: "sha256",
    checksum: "99aabbccddeeff00112233445566778899aabbccddeeff001122334455667788",
    providerName: "Aralume Renderer",
    modelName: "aralume-video-v1",
    prompt: "Historical logistics sequence",
    riskLevel: "ok",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "vd_curio_01",
    channelId: "ch_curiosidades",
    contentId: "idea_03",
    title: "Por que dormimos?",
    status: "editing",
    durationSeconds: 492,
    format: "horizontal",
    resolution: "1920x1080",
    renderStatus: "rendering",
    qualityStatus: "not_checked",
    complianceStatus: "needs_human_review",
    costActualCents: 18_320,
    type: "video",
    origin: "generated",
    licenseStatus: "pending",
    internalUri: mediaUri("ch_curiosidades", "vd_curio_01"),
    storagePath: "ch_curiosidades/video/vd_curio_01.mp4",
    mimeType: "video/mp4",
    sizeBytes: 96_441_208,
    checksumAlgorithm: "sha256",
    checksum: "8899aabbccddeeff00112233445566778899aabbccddeeff0011223344556677",
    providerName: "Aralume Renderer",
    modelName: "aralume-video-v1",
    riskLevel: "attention",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "vd_curio_02",
    channelId: "ch_curiosidades",
    contentId: "idea_04",
    title: "Paradoxo de Fermi - bloqueado",
    status: "blocked",
    durationSeconds: 0,
    format: "horizontal",
    resolution: "1920x1080",
    renderStatus: "not_started",
    qualityStatus: "not_checked",
    complianceStatus: "blocked",
    costActualCents: 12_800,
    type: "video",
    origin: "generated",
    licenseStatus: "blocked",
    internalUri: mediaUri("ch_curiosidades", "vd_curio_02"),
    storagePath: "ch_curiosidades/video/vd_curio_02.mp4",
    mimeType: "video/mp4",
    sizeBytes: 0,
    checksumAlgorithm: "sha256",
    checksum: "778899aabbccddeeff00112233445566778899aabbccddeeff00112233445566",
    providerName: "Aralume Renderer",
    modelName: "aralume-video-v1",
    riskLevel: "critical",
    createdAt: now,
    updatedAt: now,
  },
];

const derivedClips: DerivedClip[] = [
  {
    id: "cl_historia_01",
    channelId: "ch_historia",
    parentVideoId: "vd_historia_01",
    title: "As estradas romanas em 45s",
    hook: "1 imperio, 400 mil km de estradas.",
    description: "Vertical cut focusing on the logistics angle.",
    durationSeconds: 45,
    targetPlatform: "youtube_shorts",
    status: "published",
    riskLevel: "ok",
    clipPotentialScore: 88,
    type: "clip",
    origin: "generated",
    licenseStatus: "confirmed",
    internalUri: mediaUri("ch_historia", "cl_historia_01"),
    storagePath: "ch_historia/clip/cl_historia_01.mp4",
    mimeType: "video/mp4",
    sizeBytes: 28_441_208,
    checksumAlgorithm: "sha256",
    checksum: "5566778899aabbccddeeff00112233445566778899aabbccddeeff0011223344",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "cl_historia_02",
    channelId: "ch_historia",
    parentVideoId: "vd_historia_01",
    title: "Como Roma abastecia 1 milhao de pessoas",
    hook: "Uma cidade de 1 milhao sem eletricidade.",
    description: "Vertical cut focusing on the supply chain.",
    durationSeconds: 58,
    targetPlatform: "tiktok",
    status: "scheduled",
    riskLevel: "ok",
    clipPotentialScore: 91,
    type: "clip",
    origin: "generated",
    licenseStatus: "confirmed",
    internalUri: mediaUri("ch_historia", "cl_historia_02"),
    storagePath: "ch_historia/clip/cl_historia_02.mp4",
    mimeType: "video/mp4",
    sizeBytes: 31_441_208,
    checksumAlgorithm: "sha256",
    checksum: "445566778899aabbccddeeff00112233445566778899aabbccddeeff00112233",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "cl_curio_01",
    channelId: "ch_curiosidades",
    parentVideoId: "vd_curio_01",
    title: "Seu cerebro faz faxina enquanto voce dorme",
    hook: "Existe um sistema de limpeza no seu cerebro.",
    description: "Vertical cut focused on the glinfatic system.",
    durationSeconds: 52,
    targetPlatform: "instagram_reels",
    status: "clips",
    riskLevel: "attention",
    clipPotentialScore: 94,
    type: "clip",
    origin: "generated",
    licenseStatus: "pending",
    internalUri: mediaUri("ch_curiosidades", "cl_curio_01"),
    storagePath: "ch_curiosidades/clip/cl_curio_01.mp4",
    mimeType: "video/mp4",
    sizeBytes: 25_441_208,
    checksumAlgorithm: "sha256",
    checksum: "33445566778899aabbccddeeff00112233445566778899aabbccddeeff001122",
    createdAt: now,
    updatedAt: now,
  },
];

export const mediaAssetsDemoSeed: MediaAssetsSeed = {
  mediaAssets,
  videoAssets,
  derivedClips,
};
