import type { ChannelBundle } from "./channel.types.js";

const now = "2026-07-12T14:32:00.000Z";

export const channelDemoSeed: ChannelBundle[] = [
  {
    channel: {
      id: "ch_historia",
      name: "Aralume Historia",
      slug: "aralume-historia",
      description:
        "Narrativas de historia factual com curadoria academica e roteiros cinematograficos.",
      status: "active",
      niche: "Historia e civilizacoes",
      audience: "Adultos 25-55, curiosos e entusiastas",
      language: "pt-BR",
      region: "Brasil",
      timezone: "America/Sao_Paulo",
      editorialTone: "Serio, contemplativo, cinematografico",
      publishingFrequency: "3 videos longos + 5 cortes por semana",
      monthlyBudgetCents: 480000,
      monthlyCostUsedCents: 312400,
      costStatus: "healthy",
      riskLevel: "ok",
      healthScore: 92,
      activeWorkflowsCount: 7,
      pendingApprovalsCount: 3,
      connectedPlatformsCount: 4,
      lastActivityAt: "2026-07-12T13:58:00.000Z",
      createdAt: "2025-11-04T10:00:00.000Z",
      updatedAt: now,
    },
    settings: {
      id: "cs_ch_historia",
      channelId: "ch_historia",
      averageVideoDurationSeconds: 900,
      allowedFormats: ["horizontal", "vertical", "square"],
      allowedSubniches: ["Antiguidade", "Idade Media", "Guerras Mundiais", "Brasil Colonia"],
      blockedThemes: ["conteudo politico-partidario"],
      preferredSources: [
        "Britannica",
        "Cambridge University Press",
        "USP",
        "Fundacao Getulio Vargas",
      ],
      visualIdentity: {
        primaryColor: "#1B3A5C",
        secondaryColor: "#E8D9B4",
        typography: "Cormorant Garamond + Inter",
        subtitleStyle: "Bloco inferior, alto contraste, 42px",
        openingStyle: "Fade 1.2s com stinger sonoro discreto",
        thumbnailStyle: "Retrato dominante + tipografia contrastante",
      },
      narration: {
        voiceName: "Ravi PT-BR",
        voiceProvider: "ElevenLabs (mock)",
        speed: 0.98,
        tone: "Grave e contemplativo",
        pronunciationNotes: ["Aralume: A-ra-lu-me", "Numeros em extenso ate 12"],
      },
      createdAt: "2025-11-04T10:00:00.000Z",
      updatedAt: now,
    },
    editorialRules: {
      id: "er_ch_historia",
      channelId: "ch_historia",
      factualContentRequiresSources: true,
      minimumSources: 4,
      allowFictionalNarratives: false,
      allowThirdPartyAssets: true,
      requiresHumanApprovalBeforePublication: true,
      highRiskAutoBlock: true,
      prohibitedClaims: ["projecoes financeiras especificas sem fonte"],
      complianceNotes: [
        "Sempre distinguir fato, hipotese e opiniao no roteiro.",
        "Fontes devem ser reproduziveis e datadas.",
      ],
      createdAt: "2025-11-04T10:00:00.000Z",
      updatedAt: now,
    },
  },
  {
    channel: {
      id: "ch_curiosidades",
      name: "Aralume Curiosidades",
      slug: "aralume-curiosidades",
      description:
        "Curiosidades cientificas e culturais em formato multiplataforma com forte potencial de cortes.",
      status: "warning",
      niche: "Ciencia e curiosidades gerais",
      audience: "Jovens adultos 18-34",
      language: "pt-BR",
      region: "Brasil",
      timezone: "America/Sao_Paulo",
      editorialTone: "Dinamico, provocativo, acessivel",
      publishingFrequency: "2 videos longos + 14 cortes por semana",
      monthlyBudgetCents: 620000,
      monthlyCostUsedCents: 587200,
      costStatus: "attention",
      riskLevel: "warning",
      healthScore: 71,
      activeWorkflowsCount: 11,
      pendingApprovalsCount: 6,
      connectedPlatformsCount: 3,
      lastActivityAt: "2026-07-12T14:10:00.000Z",
      createdAt: "2026-01-18T09:00:00.000Z",
      updatedAt: now,
    },
    settings: {
      id: "cs_ch_curiosidades",
      channelId: "ch_curiosidades",
      averageVideoDurationSeconds: 480,
      allowedFormats: ["horizontal", "vertical", "square"],
      allowedSubniches: ["Corpo humano", "Espaco", "Psicologia", "Curiosidades historicas"],
      blockedThemes: ["teorias da conspiracao", "pseudociencia", "conteudo medico prescritivo"],
      preferredSources: ["Nature", "Scientific American", "MIT Technology Review"],
      visualIdentity: {
        primaryColor: "#B8412C",
        secondaryColor: "#F2C14E",
        typography: "Space Grotesk + Inter",
        subtitleStyle: "Bloco inferior, alto contraste, 42px",
        openingStyle: "Fade 1.2s com stinger sonoro discreto",
        thumbnailStyle: "Retrato dominante + tipografia contrastante",
      },
      narration: {
        voiceName: "Luiza PT-BR",
        voiceProvider: "ElevenLabs (mock)",
        speed: 1.05,
        tone: "Energetico e curioso",
        pronunciationNotes: ["Aralume: A-ra-lu-me", "Numeros em extenso ate 12"],
      },
      createdAt: "2026-01-18T09:00:00.000Z",
      updatedAt: now,
    },
    editorialRules: {
      id: "er_ch_curiosidades",
      channelId: "ch_curiosidades",
      factualContentRequiresSources: true,
      minimumSources: 3,
      allowFictionalNarratives: false,
      allowThirdPartyAssets: true,
      requiresHumanApprovalBeforePublication: true,
      highRiskAutoBlock: true,
      prohibitedClaims: ["curas milagrosas", "eventos nao verificaveis apresentados como fato"],
      complianceNotes: [
        "Sempre distinguir fato, hipotese e opiniao no roteiro.",
        "Fontes devem ser reproduziveis e datadas.",
      ],
      createdAt: "2026-01-18T09:00:00.000Z",
      updatedAt: now,
    },
  },
  {
    channel: {
      id: "ch_negocios",
      name: "Aralume Negocios",
      slug: "aralume-negocios",
      description:
        "Analises de mercado, cases empresariais e estrategia para tomadores de decisao.",
      status: "draft",
      niche: "Negocios e estrategia corporativa",
      audience: "Executivos, empreendedores e analistas",
      language: "pt-BR",
      region: "Brasil",
      timezone: "America/Sao_Paulo",
      editorialTone: "Institucional, analitico, direto",
      publishingFrequency: "A configurar",
      monthlyBudgetCents: 350000,
      monthlyCostUsedCents: 0,
      costStatus: "not_configured",
      riskLevel: "attention",
      healthScore: 42,
      activeWorkflowsCount: 0,
      pendingApprovalsCount: 0,
      connectedPlatformsCount: 1,
      lastActivityAt: "2026-07-10T18:22:00.000Z",
      createdAt: "2026-06-28T14:00:00.000Z",
      updatedAt: now,
    },
    settings: {
      id: "cs_ch_negocios",
      channelId: "ch_negocios",
      averageVideoDurationSeconds: 720,
      allowedFormats: ["horizontal", "vertical", "square"],
      allowedSubniches: ["M&A", "Startups", "Estrategia", "Lideranca"],
      blockedThemes: ["conteudo politico-partidario"],
      preferredSources: ["Harvard Business Review", "McKinsey Quarterly", "The Economist"],
      visualIdentity: {
        primaryColor: "#0F2A3F",
        secondaryColor: "#C7D3DD",
        typography: "Sohne + Inter",
        subtitleStyle: "Bloco inferior, alto contraste, 42px",
        openingStyle: "Fade 1.2s com stinger sonoro discreto",
        thumbnailStyle: "Retrato dominante + tipografia contrastante",
      },
      narration: {
        voiceName: "Bernardo PT-BR",
        voiceProvider: "ElevenLabs (mock)",
        speed: 1,
        tone: "Formal executivo",
        pronunciationNotes: ["Aralume: A-ra-lu-me", "Numeros em extenso ate 12"],
      },
      createdAt: "2026-06-28T14:00:00.000Z",
      updatedAt: now,
    },
    editorialRules: {
      id: "er_ch_negocios",
      channelId: "ch_negocios",
      factualContentRequiresSources: true,
      minimumSources: 3,
      allowFictionalNarratives: false,
      allowThirdPartyAssets: true,
      requiresHumanApprovalBeforePublication: true,
      highRiskAutoBlock: true,
      prohibitedClaims: ["projecoes financeiras especificas sem fonte"],
      complianceNotes: [
        "Sempre distinguir fato, hipotese e opiniao no roteiro.",
        "Fontes devem ser reproduziveis e datadas.",
      ],
      createdAt: "2026-06-28T14:00:00.000Z",
      updatedAt: now,
    },
  },
];
